import type { Config } from 'tailwindcss'

export default <Config>{
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        surface: '#f7f9fb',
        secondary: '#5a5f68',
        'surface-container-lowest': '#ffffff',
        primary: '#0058be',
        'on-primary': '#ffffff',
        outline: '#727785',
        'outline-variant': '#c2c6d6',
        'primary-container': '#2170e4',
        'primary-fixed': '#d8e2ff',
        'primary-fixed-dim': '#adc6ff',
        'on-primary-fixed': '#001a42',
        'on-primary-fixed-variant': '#004395',
        'on-primary-container': '#fefcff',
        'surface-variant': '#e0e3e5',
        'surface-bright': '#f7f9fb',
        'surface-dim': '#d8dadc',
        'surface-container': '#eceef0',
        'surface-container-low': '#f2f4f6',
        'surface-container-high': '#e6e8ea',
        'surface-container-highest': '#e0e3e5',
        'on-surface': '#191c1e',
        'on-surface-variant': '#424754',
        tertiary: '#6b38d4',
        'tertiary-container': '#8455ef',
        'on-tertiary': '#ffffff',
        'on-tertiary-container': '#fffbff',
        'secondary-container': '#dee2ed',
        'on-secondary-container': '#60656e',
        error: '#ba1a1a',
        'error-container': '#ffdad6',
        'on-error': '#ffffff',
        'on-error-container': '#93000a',
        'inverse-surface': '#2d3133',
        'inverse-on-surface': '#eff1f3',
        'inverse-primary': '#adc6ff',
        background: '#f7f9fb',
        'on-background': '#191c1e',
      },
      fontFamily: {
        headline: ['Manrope', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '1rem',
        lg: '2rem',
        xl: '3rem',
        full: '9999px',
      },
      scale: {
        '102': '1.02',
      },
    },
  },
}
