// Helper untuk definisi candle ringkas
const G = '#10b981', R = '#ef4444', GR = '#64748b'
const h = (wt:number,bt:number,bb:number,wb:number,c:string) => ({wickTop:wt,bodyTop:bt,bodyBot:bb,wickBot:wb,color:c})
const D = (title:string,body:string) => ({title,body})

import type { CandleDef, DetailSection, PatternDef, CategoryDef } from './patternData'

export const candleCategories: CategoryDef[] = [
  // ═══ 1. SINGLE CANDLE (18 pola) ═══
  {title:'Pola Satu Candle',subtitle:'18 POLA — SINYAL CEPAT SATU SESI',open:false,patterns:[
    {name:'Hammer',label:'Hammer',labelColor:'text-emerald-500',desc:'Ekor panjang bawah, body kecil atas. Reversal bullish di dasar downtrend.',signal:'Bullish',candles:[h(18,18,26,58,G)],detail:[D('Bentuk','Body kecil di puncak, ekor bawah >=2-3x body. Tanpa ekor atas (atau nyaris nol).'),D('Arti','Seller sempat menekan harga turun dalam, namun buyer masuk agresif dan menutup harga di puncak sesi. Sinyal pembalikan bullish di dasar downtrend.'),D('Konfirmasi','Tunggu candle hijau berikutnya menutup di atas body Hammer. Hanya valid di akhir downtrend.')]},
    {name:'Inverted Hammer',label:'Inv. Hammer',labelColor:'text-emerald-500',desc:'Ekor panjang atas, body kecil di dasar. Butuh konfirmasi candle hijau berikutnya.',signal:'Bullish',candles:[h(4,36,44,46,G)],detail:[D('Bentuk','Kebalikan Hammer: body kecil di dasar sesi, ekor atas panjang (>=2x body), nyaris tanpa ekor bawah.'),D('Arti','Buyer mencoba melakukan penetrasi naik ke atas. Meskipun sempat tertahan, ini tanda tekanan beli mulai memasuki pasar di dasar downtrend.')]},
    {name:'Hanging Man',label:'Hanging Man',labelColor:'text-red-500',desc:'Bentuk identik hammer tapi di puncak uptrend. Sinyal pembalikan bearish.',signal:'Bearish',candles:[h(18,18,26,58,R)],detail:[D('Bentuk','Identik dengan Hammer (body kecil atas, ekor bawah panjang), namun muncul di PUNCAK uptrend.'),D('Arti','Ekor bawah panjang membuktikan seller untuk pertama kalinya berhasil membanting harga jatuh dalam. Peringatan keras bahwa daya dorong buyer mulai rapuh.')]},
    {name:'Shooting Star',label:'Shooting Star',labelColor:'text-red-500',desc:'Ekor panjang atas di puncak, body kecil di dasar. Kebalikan hammer, sinyal bearish reversal.',signal:'Bearish',candles:[h(4,36,44,46,R)],detail:[D('Bentuk','Body kecil di dasar, ekor atas panjang (>=2-3x body) membentur resistance di PUNCAK uptrend.'),D('Arti','Buyer memompa harga ke level tertinggi baru namun langsung dibantai oleh seller hingga closing mendekati level terendah. Penolakan harga pucuk yang masif.')]},
    {name:'Bullish Marubozu',label:'Bull Marubozu',labelColor:'text-emerald-500',desc:'Body besar penuh tanpa ekor sama sekali. Dominasi buyer 100%, momentum sangat kuat.',signal:'Bullish',candles:[h(8,8,52,52,G)],detail:[D('Bentuk','Body hijau besar padat TANPA ekor atas maupun bawah (Open = Low, Close = High).'),D('Arti','Buyer mendominasi penuh sepanjang sesi dari detik awal pembukaan hingga penutupan. Sinyal momentum ekspansi tren naik paling murni.')]},
    {name:'Bearish Marubozu',label:'Bear Marubozu',labelColor:'text-red-500',desc:'Body merah besar penuh tanpa ekor. Dominasi seller 100%, momentum turun kuat.',signal:'Bearish',candles:[h(8,8,52,52,R)],detail:[D('Bentuk','Body merah besar padat TANPA ekor (Open = High, Close = Low).'),D('Arti','Seller mendominasi total tanpa perlawanan buyer sama sekali. Sering menjadi awal akselerasi downtrend deras.')]},
    {name:'Doji',label:'Doji',labelColor:'text-gray-400',desc:'Open = Close. Ekor sedang di kedua sisi. Titik keraguan pasar saat volatilitas normal.',signal:'Netral',candles:[h(10,29,31,50,GR)],detail:[D('Karakteristik','Ekor atas dan bawah pendek hingga sedang. Open dan Close di harga yang sama (nyaris tanpa bodi).'),D('Arti Pasar','Buyer dan seller seimbang pada rentang harga normal. Di puncak atau dasar tren, ini tanda awal pelemahan momentum.'),D('Konfirmasi','Doji BUKAN sinyal arah mandiri. Selalu tunggu candle konfirmasi berikutnya.')]},
    {name:'Long-Legged Doji',label:'Long-Legged',labelColor:'text-gray-400',desc:'Doji ekor sangat panjang asimetris. Volatilitas meledak liar, posisi bodi bisa condong ke atas/bawah.',signal:'Netral',candles:[h(2,20,22,58,GR)],detail:[D('Karakteristik','Rentang harga (High-Low) sangat lebar. Ekor atas dan bawah panjang, tetapi letak bodi TIDAK harus di tengah (bisa asimetris).'),D('Arti Pasar','Pertarungan liar dua arah dalam satu sesi. Volatilitas tinggi, namun belum ada pihak yang mampu menahan dominasi saat penutupan.'),D('Tindakan Trader','Volatilitas ekstrem tanda pergantian likuiditas besar (smart money churn). Pasang alert di high/low candle.')]},
    {name:'Dragonfly Doji',label:'Dragonfly',labelColor:'text-emerald-500',desc:'Open=High=Close, ekor panjang bawah. Rejection kuat di support, bullish kuat.',signal:'Bullish',candles:[h(14,14,16,56,G)],detail:[D('Bentuk','Open, High, Close persis sama di puncak (huruf "T"). Ekor bawah sangat panjang.'),D('Arti','Rejection harga bawah sangat masif. Di dasar downtrend = sinyal penyerapan likuiditas (bullish reversal) terkuat.')]},
    {name:'Gravestone Doji',label:'Gravestone',labelColor:'text-red-500',desc:'Open=Low=Close, ekor panjang atas. Rejection kuat di resistance, bearish kuat.',signal:'Bearish',candles:[h(4,44,46,46,R)],detail:[D('Bentuk','Open, Low, Close persis sama di dasar (huruf "T" terbalik). Ekor atas sangat panjang.'),D('Arti','"Batu nisan" bagi buyer. Buyer mencoba memompa harga namun dibuang habis oleh seller hingga tutup di dasar sesi.')]},
    {name:'Four Price Doji',label:'Four Price',labelColor:'text-gray-400',desc:'Open=High=Low=Close. Garis datar tanpa ekor. Pasar benar-benar beku / terkunci.',signal:'Netral',candles:[h(30,30,30,30,GR)],detail:[D('Arti','Tidak ada fluktuasi harga sama sekali sepanjang sesi. Khas saham auto-rejection terkunci (ARA/ARB), saham suspensi bursa, atau aset illikuid.')]},
    {name:'Spinning Top',label:'Spinning Top',labelColor:'text-gray-400',desc:'Beda dengan Doji: MEMILIKI BODI KOTAK KECIL (bukan garis tipis) dengan ekor atas-bawah simetris.',signal:'Netral',candles:[h(6,24,36,54,GR)],detail:[D('Perbedaan dengan Doji','Doji tidak punya bodi (Open = Close berupa garis tipis). Spinning Top MEMILIKI BODI KOTAK NYATA (Open & Close ada selisih).'),D('Arti Pasar','Pertarungan seimbang buyer vs seller. Masih ada selisih harga buka-tutup, namun momentum tren utama telah menguap.')]},
    {name:'Bullish Belt Hold',label:'Bull Belt Hold',labelColor:'text-emerald-500',desc:'Buka tepat di low (shaved bottom), rally hijau panjang mendekati high.',signal:'Bullish',candles:[h(8,12,50,50,G)],detail:[D('Bentuk','Open = Low (tanpa ekor bawah sama sekali / shaved bottom). Bodi hijau panjang solid dengan ekor atas sangat pendek.'),D('Arti','Buyer langsung mengambil kendali agresif dari detik pertama bel pembukaan berbunyi. Sinyal bullish perkasa di awal tren baru.')]},
    {name:'Bearish Belt Hold',label:'Bear Belt Hold',labelColor:'text-red-500',desc:'Buka tepat di high (shaved top), jatuh merah panjang mendekati low.',signal:'Bearish',candles:[h(10,10,48,52,R)],detail:[D('Bentuk','Open = High (tanpa ekor atas sama sekali / shaved top). Bodi merah panjang solid dengan ekor bawah sangat pendek.'),D('Arti','Seller langsung mendominasi dari detik pertama sesi dan membanting harga turun. Sinyal bearish kuat di pucuk resistance.')]},
    {name:'White Paper Umbrella',label:'Paper Umbrella',labelColor:'text-emerald-500',desc:'Induk tradisional Jepang (Karakasa): bodi di puncak, ekor bawah panjang seperti gagang payung.',signal:'Bullish',candles:[h(16,16,24,58,G)],detail:[D('Arti','Karakasa adalah nama keluarga orisinal di Jepang untuk Hammer (bodi kecil di atas, ekor bawah sangat panjang menyerupai gagang payung kertas tanpa ekor atas).')]},
    {name:'Black Paper Umbrella',label:'Black Umbrella',labelColor:'text-red-500',desc:'Induk tradisional Jepang (Karakasa merah): bodi merah di puncak, ekor bawah panjang di puncak tren.',signal:'Bearish',candles:[h(16,16,24,58,R)],detail:[D('Arti','Versi bearish dari Karakasa (identik Hanging Man). Ekor bawah panjang di puncak menandakan kerentanan tren naik.')]},
    {name:'Rickshaw Man',label:'Rickshaw Man',labelColor:'text-gray-400',desc:'Varian spesifik Long-Legged Doji: ekor sangat panjang & bodi PERSIS di tengah 50% (simetris absolut).',signal:'Netral',candles:[h(2,29,31,58,GR)],detail:[D('Karakteristik','Nama terinspirasi penarik becak tradisional Jepang yang memikul beban persis di tengah. Ekor atas dan bawah sama panjangnya, bodi garis tepat di 50% range.'),D('Arti Pasar','Stalemate / kebuntuan absolut! Volatilitas ekstrem namun berakhir imbang mutlak. Menandakan tren sebelumnya lumpuh total dan siap meledak ke salah satu arah.')]},
    {name:'Tri-Star Doji',label:'Tri-Star',labelColor:'text-gray-400',desc:'Tiga doji dengan doji tengah melompat (gap up/down sebagai Bintang). Sangat langka.',signal:'Netral',candles:[h(16,30,32,46,GR),h(4,18,20,34,GR),h(16,30,32,46,GR)],detail:[D('Bentuk','Tiga Doji berturut-turut di mana Doji KEDUA (tengah) melompat gap lebih tinggi membentuk formasi bintang (Star).'),D('Arti','Pola pembalikan arah paling langka dan dihormati dalam tradisi candlestick Jepang. Mengindikasikan pembalikan tren besar.')]},
  ]},
  // ═══ 2. DOUBLE CANDLE (17 pola) ═══
  {title:'Pola Dua Candle',subtitle:'17 POLA — DIKONFIRMASI DUA SESI',open:false,patterns:[
    {name:'Bullish Engulfing',label:'Bull Engulfing',labelColor:'text-emerald-500',desc:'Candle hijau besar "menelan" candle merah sebelumnya. Reversal naik sangat kuat.',signal:'Bullish',candles:[h(15,20,35,40,R),h(5,12,42,48,G)],detail:[D('Bentuk','Merah kecil + hijau besar yang body-nya menelan seluruh body merah.'),D('Arti','Perpindahan kekuatan dramatis. Semakin besar engulfing, semakin kuat sinyal.')]},
    {name:'Bearish Engulfing',label:'Bear Engulfing',labelColor:'text-red-500',desc:'Candle merah besar menelan candle hijau. Reversal turun sangat kuat di puncak.',signal:'Bearish',candles:[h(10,18,33,38,G),h(5,12,42,48,R)],detail:[D('Bentuk','Hijau kecil + merah besar yang menelan seluruh body hijau.'),D('Arti','Seller kalahkan buyer telak. Sering menandai puncak uptrend.')]},
    {name:'Bullish Harami',label:'Bull Harami',labelColor:'text-emerald-500',desc:'Candle kecil hijau terkandung dalam body candle merah besar sebelumnya.',signal:'Bullish',candles:[h(5,8,45,50,R),h(20,22,32,35,G)],detail:[D('Bentuk','"Harami" = hamil. Candle kecil di dalam body candle besar.'),D('Arti','Momentum bearish melemah. Seller kehilangan tenaga.')]},
    {name:'Bearish Harami',label:'Bear Harami',labelColor:'text-red-500',desc:'Candle kecil merah terkandung dalam body candle hijau besar sebelumnya.',signal:'Bearish',candles:[h(5,8,45,50,G),h(20,22,32,35,R)],detail:[D('Arti','Momentum bullish melemah. Buyer kehilangan kendali. Potensi reversal di puncak.')]},
    {name:'Bullish Harami Cross',label:'Bull Harami Cross',labelColor:'text-emerald-500',desc:'Doji terkandung dalam body candle merah besar. Versi lebih kuat dari harami.',signal:'Bullish',candles:[h(5,8,45,50,R),h(22,27,29,35,GR)],detail:[D('Arti','Harami + Doji = sinyal lebih kuat. Ketidakpastian di dalam body bearish = momentum jual benar-benar habis.')]},
    {name:'Bearish Harami Cross',label:'Bear Harami Cross',labelColor:'text-red-500',desc:'Doji terkandung dalam body candle hijau besar. Sinyal reversal bearish.',signal:'Bearish',candles:[h(5,8,45,50,G),h(22,27,29,35,GR)],detail:[D('Arti','Doji di dalam body bullish = buyer ragu setelah rally. Sering di puncak.')]},
    {name:'Piercing Line',label:'Piercing Line',labelColor:'text-emerald-500',desc:'Candle hijau buka di bawah low candle merah, tutup di atas 50% body merah.',signal:'Bullish',candles:[h(8,12,38,42,R),h(30,32,48,50,G)],detail:[D('Arti','Gap down awal = seller masih kuat, tapi buyer balikkan dan tembus >50% body merah.')]},
    {name:'Dark Cloud Cover',label:'Dark Cloud',labelColor:'text-red-500',desc:'Candle merah buka di atas high hijau, tutup di bawah 50% body hijau.',signal:'Bearish',candles:[h(8,12,38,42,G),h(5,10,30,35,R)],detail:[D('Arti','Kebalikan Piercing Line. Gap up tapi seller dorong turun >50%. Tren naik melemah.')]},
    {name:'Tweezer Bottom',label:'Tweezer Bottom',labelColor:'text-emerald-500',desc:'Dua candle dengan low persis sama di support. Rejection kuat dari bawah.',signal:'Bullish',candles:[h(10,15,35,50,R),h(10,18,38,50,G)],detail:[D('Arti','Support diuji 2x tapi gagal ditembus. Buyer kuat di level tersebut.')]},
    {name:'Tweezer Top',label:'Tweezer Top',labelColor:'text-red-500',desc:'Dua candle dengan high persis sama di resistance. Rejection kuat dari atas.',signal:'Bearish',candles:[h(8,15,35,42,G),h(8,18,38,45,R)],detail:[D('Arti','Resistance diuji 2x tapi gagal ditembus. Seller kuat di level atas.')]},
    {name:'Bullish Kicker',label:'Bull Kicker',labelColor:'text-emerald-500',desc:'Gap besar ke atas dari candle merah ke candle hijau. Perubahan sentimen drastis.',signal:'Bullish',candles:[h(10,15,40,45,R),h(5,8,32,38,G)],detail:[D('Arti','Sinyal paling kuat di semua pola 2 candle. Gap up dari bearish ke bullish = perubahan sentimen total.')]},
    {name:'Bearish Kicker',label:'Bear Kicker',labelColor:'text-red-500',desc:'Gap besar ke bawah dari candle hijau ke candle merah. Pembalikan drastis.',signal:'Bearish',candles:[h(8,10,35,40,G),h(15,18,45,50,R)],detail:[D('Arti','Gap down dari bullish ke bearish. Perubahan sentimen paling drastis yang mungkin.')]},
    {name:'On-Neck Pattern',label:'On-Neck',labelColor:'text-red-500',desc:'Candle hijau menutup tepat di low candle merah sebelumnya. Lanjut turun.',signal:'Bearish',candles:[h(5,8,35,40,R),h(32,35,40,42,G)],detail:[D('Arti','Buyer coba rebound tapi hanya sampai low candle sebelumnya. Tekanan jual masih dominan.')]},
    {name:'In-Neck Pattern',label:'In-Neck',labelColor:'text-red-500',desc:'Serupa on-neck, candle hijau menembus sedikit ke dalam body merah.',signal:'Bearish',candles:[h(5,8,35,40,R),h(30,33,38,42,G)],detail:[D('Arti','Buyer sedikit lebih kuat dari On-Neck tapi masih gagal tembus 50%. Bearish continuation.')]},
    {name:'Thrusting Pattern',label:'Thrusting',labelColor:'text-red-500',desc:'Candle hijau menembus kurang dari 50% ke atas. Kelemahan buyer.',signal:'Bearish',candles:[h(5,8,38,42,R),h(28,30,36,42,G)],detail:[D('Arti','Buyer tembus ke body merah tapi <50%. Masih bearish karena tekanan beli tidak cukup kuat.')]},
    {name:'Meeting Lines Bullish',label:'Meeting Lines↑',labelColor:'text-emerald-500',desc:'Dua candle berlawanan menutup di harga sama. Pertarungan seimbang, potensi naik.',signal:'Bullish',candles:[h(8,12,38,42,R),h(28,32,38,45,G)],detail:[D('Arti','Candle merah + hijau menutup di level sama. Di dasar = potensi reversal naik.')]},
    {name:'Meeting Lines Bearish',label:'Meeting Lines↓',labelColor:'text-red-500',desc:'Dua candle berlawanan menutup di harga sama di puncak. Potensi turun.',signal:'Bearish',candles:[h(8,12,38,42,G),h(5,12,38,42,R)],detail:[D('Arti','Di puncak, close yang sama = buyer dan seller setara, momentum naik habis.')]},
  ]},
  // ═══ 3. TRIPLE CANDLE (23 pola) ═══
  {title:'Pola Tiga Candle & Multi',subtitle:'23 POLA — KONFIRMASI TERKUAT',open:false,patterns:[
    {name:'Morning Star',label:'Morning Star',labelColor:'text-emerald-500',desc:'Merah besar → kecil/doji → hijau besar. Reversal bullish paling dipercaya.',signal:'Bullish',candles:[h(5,10,35,40,R),h(32,38,42,50,GR),h(12,15,40,45,G)],detail:[D('Bentuk','C1: Merah besar. C2: Body kecil/doji (gap down). C3: Hijau besar (gap up).'),D('Arti','Pola "fajar". Seller dorong turun → momentum berhenti → buyer masuk kuat.')]},
    {name:'Evening Star',label:'Evening Star',labelColor:'text-red-500',desc:'Hijau besar → kecil/doji → merah besar. Reversal bearish paling dipercaya.',signal:'Bearish',candles:[h(12,15,40,45,G),h(5,10,15,20,GR),h(8,12,38,42,R)],detail:[D('Arti','Pola "senja". Momentum beli capai puncak → ragu → seller ambil alih.')]},
    {name:'Morning Doji Star',label:'Morning Doji★',labelColor:'text-emerald-500',desc:'Versi morning star dengan doji di tengah. Lebih kuat dari morning star biasa.',signal:'Bullish',candles:[h(5,10,35,40,R),h(35,40,42,48,GR),h(12,15,38,42,G)],detail:[D('Arti','Doji di tengah = ketidakpastian absolut sebelum reversal. Lebih kuat dari Morning Star.')]},
    {name:'Evening Doji Star',label:'Evening Doji★',labelColor:'text-red-500',desc:'Versi evening star dengan doji di tengah. Lebih kuat karena gap doji.',signal:'Bearish',candles:[h(12,15,40,45,G),h(5,8,10,15,GR),h(8,12,38,42,R)],detail:[D('Arti','Doji di puncak = titik keraguan absolut. Gap down berikutnya konfirmasi reversal.')]},
    {name:'Three White Soldiers',label:'3 White Soldiers',labelColor:'text-emerald-500',desc:'Tiga candle hijau berurutan body besar naik. Pembalikan bullish sangat kuat.',signal:'Bullish',candles:[h(28,30,48,52,G),h(16,18,35,38,G),h(4,6,22,25,G)],detail:[D('Arti','Buyer dominasi total 3 sesi. Akumulasi pembelian konsisten dan kuat.')]},
    {name:'Three Black Crows',label:'3 Black Crows',labelColor:'text-red-500',desc:'Tiga candle merah berurutan body besar turun. Pembalikan bearish sangat kuat.',signal:'Bearish',candles:[h(4,6,22,25,R),h(16,18,35,38,R),h(28,30,48,52,R)],detail:[D('Arti','Tekanan jual 3 hari berturut. Pertimbangkan cut loss jika muncul.')]},
    {name:'Three Inside Up',label:'3 Inside Up',labelColor:'text-emerald-500',desc:'Harami bullish → konfirmasi candle hijau. Reversal naik terkonfirmasi.',signal:'Bullish',candles:[h(5,8,42,48,R),h(18,20,32,35,G),h(3,5,25,28,G)],detail:[D('Arti','Harami + konfirmasi C3. Lebih andal dari Harami biasa.')]},
    {name:'Three Inside Down',label:'3 Inside Down',labelColor:'text-red-500',desc:'Harami bearish → konfirmasi candle merah. Reversal turun terkonfirmasi.',signal:'Bearish',candles:[h(5,8,42,48,G),h(18,20,32,35,R),h(25,28,48,52,R)],detail:[D('Arti','Harami bearish terkonfirmasi candle merah ketiga.')]},
    {name:'Three Outside Up',label:'3 Outside Up',labelColor:'text-emerald-500',desc:'Engulfing bullish → konfirmasi candle hijau ketiga. Sangat kuat.',signal:'Bullish',candles:[h(15,18,32,35,R),h(5,10,40,45,G),h(3,5,25,28,G)],detail:[D('Arti','Bullish Engulfing + candle konfirmasi. Salah satu pola reversal 3-candle terkuat.')]},
    {name:'Three Outside Down',label:'3 Outside Down',labelColor:'text-red-500',desc:'Engulfing bearish → konfirmasi candle merah ketiga. Sangat kuat.',signal:'Bearish',candles:[h(15,18,32,35,G),h(5,10,40,45,R),h(25,28,48,52,R)],detail:[D('Arti','Bearish Engulfing + konfirmasi. Sinyal reversal turun terkuat.')]},
    {name:'Bullish Abandoned Baby',label:'Abandoned Baby↑',labelColor:'text-emerald-500',desc:'Doji yang gap down dari candle merah, lalu gap up ke hijau. Pola langka kuat.',signal:'Bullish',candles:[h(5,8,30,35,R),h(38,42,45,50,GR),h(12,15,35,40,G)],detail:[D('Arti','Sangat langka. Doji terisolasi (gap kedua sisi) = titik balik absolut.')]},
    {name:'Bearish Abandoned Baby',label:'Abandoned Baby↓',labelColor:'text-red-500',desc:'Doji yang gap up dari hijau, lalu gap down ke merah. Pola langka kuat.',signal:'Bearish',candles:[h(12,15,40,45,G),h(3,6,8,12,GR),h(8,12,38,42,R)],detail:[D('Arti','Kebalikan bullish. Doji terisolasi di puncak = reversal bearish sangat kuat.')]},
    {name:'Rising Three Methods',label:'Rising 3 Methods',labelColor:'text-emerald-500',desc:'Candle hijau besar → 3 candle kecil merah → candle hijau besar. Lanjut naik.',signal:'Continuation',candles:[h(8,10,38,42,G),h(15,18,25,28,R),h(18,20,28,30,R),h(20,22,30,32,R),h(5,8,30,35,G)],detail:[D('Arti','Koreksi kecil (3 merah) tidak merusak tren naik. Candle hijau terakhir konfirmasi kelanjutan.')]},
    {name:'Falling Three Methods',label:'Falling 3 Methods',labelColor:'text-red-500',desc:'Candle merah besar → 3 candle kecil hijau → candle merah besar. Lanjut turun.',signal:'Continuation',candles:[h(5,8,38,42,R),h(28,30,38,42,G),h(25,28,35,38,G),h(22,25,32,35,G),h(18,20,48,52,R)],detail:[D('Arti','Rebound kecil (3 hijau) gagal. Candle merah terakhir konfirmasi downtrend berlanjut.')]},
    {name:'Upside Tasuki Gap',label:'Upside Tasuki',labelColor:'text-emerald-500',desc:'Gap naik antara dua candle hijau, candle merah menutup sebagian gap. Lanjut naik.',signal:'Bullish',candles:[h(20,22,42,45,G),h(5,8,20,22,G),h(10,12,25,28,R)],detail:[D('Arti','Gap tidak tertutup penuh oleh candle merah = buyer masih dominan. Kelanjutan uptrend.')]},
    {name:'Downside Tasuki Gap',label:'Downside Tasuki',labelColor:'text-red-500',desc:'Gap turun antara dua candle merah, candle hijau tidak menutup gap. Lanjut turun.',signal:'Bearish',candles:[h(8,10,30,32,R),h(28,32,50,52,R),h(25,28,42,45,G)],detail:[D('Arti','Gap down tidak tertutup oleh candle hijau. Seller tetap dominan.')]},
    {name:'Mat Hold',label:'Mat Hold',labelColor:'text-emerald-500',desc:'Candle besar hijau → 4 candle kecil → candle hijau besar. Kelanjutan kuat.',signal:'Continuation',candles:[h(15,18,42,45,G),h(12,15,22,25,R),h(15,18,25,28,R),h(18,20,28,30,R),h(2,5,28,32,G)],detail:[D('Arti','Varian Rising 3 Methods yang lebih kompleks. 4 candle koreksi kecil diikuti candle besar kelanjutan.')]},
    {name:'Stick Sandwich',label:'Stick Sandwich',labelColor:'text-emerald-500',desc:'Dua candle merah mengapit satu candle hijau. Potensi reversal ke atas.',signal:'Bullish',candles:[h(8,12,38,42,R),h(10,15,35,40,G),h(8,12,38,42,R)],detail:[D('Arti','Close candle merah pertama dan ketiga di level sama. Double test support = potensi rebound.')]},
    {name:'Three Stars South',label:'3 Stars South',labelColor:'text-emerald-500',desc:'Tiga candle merah mengecil dengan lower shadow. Selling pressure habis.',signal:'Bullish',candles:[h(5,8,38,55,R),h(12,15,35,48,R),h(18,20,32,40,R)],detail:[D('Arti','Body mengecil + ekor bawah memendek = seller kehabisan amunisi. Potensi reversal.')]},
    {name:'Identical Three Crows',label:'Identical 3 Crows',labelColor:'text-red-500',desc:'Tiga candle merah dengan open di body candle sebelumnya. Tren turun kuat.',signal:'Bearish',candles:[h(5,8,25,28,R),h(15,18,35,38,R),h(28,30,48,52,R)],detail:[D('Arti','Setiap candle buka di close candle sebelumnya. Tekanan jual sangat konsisten.')]},
    {name:'Deliberation Pattern',label:'Deliberation',labelColor:'text-red-500',desc:'Dua candle hijau besar → candle kecil di atas. Momentum naik mulai habis.',signal:'Bearish',candles:[h(12,15,38,42,G),h(5,8,22,25,G),h(3,5,10,14,G)],detail:[D('Arti','Body mengecil = buyer melemah. Meskipun masih hijau, momentum hampir habis.')]},
    {name:'Advance Block',label:'Advance Block',labelColor:'text-red-500',desc:'Tiga candle hijau tapi mengecil. Uptrend melemah, buyer kelelahan.',signal:'Bearish',candles:[h(25,28,48,52,G),h(15,18,35,38,G),h(8,10,20,22,G)],detail:[D('Arti','Mirip 3 White Soldiers tapi body semakin kecil = momentum habis. Hati-hati reversal.')]},
  ]},
]
